# Hi, I'm the jailr configuration file!
# jailr does have required configuration, but there are comments like me that make it easy!

# Here you can set what permissions group you want jailed players to be set to:
group: jailed

# Here you can set whether or not the plugin will broadcast a message
# when someone is jailed or unjailed.
broadcast: true

# Here you can set if jailed players are automatically quarantined. Quarantined status means that the player can move,
# but the player cannot interact with the world (open chests, break blocks, etc.) All players with the permission
# jailr.quarantined are already quarantined.
auto-quarantine: true

# Here you can set if jailed players are automatically frozen. Frozen status means that the player can look around,
# but the player cannot move. All players with the permission jailr.frozen are already frozen.
auto-freeze: false

# STOP! That's all the configuration needed unless you're using mysql.
# If you're using mysql, change the below database configuration to this and change the default values:

# MySQL example database configuration
# database:
#   # Put the user that you want jailr to access the database using.
#   username: jailr
#   # Here you should put the password of the above user.
#   password: my_password
#   # Here goes the hostname of the MySQL server ("localhost" if it's the same machine as the minecraft server)
#   host: localhost
#   # This is the port of the MySQL server (3306 is the default)
#   port: 3306
#   # This is the database you want jailr to use. It should have been created already (jailr will add tables)
#   database: jailr
#   # This is the table prefix that you want jailr to use. You don't have to change it.
#   prefix: jail_

database:
  driver: h2

# That's it! Seriously! Don't change anything after this line or it could screw up your jailr installation.
seriously-don't-touch-this: 1
debug: false