name: jailr
version: 0.1
authors: [Sushi, Tyzoid, messageofdeath]
website: http://jailr.tyzoid.com/
main: com.tyzoid.jailr.JailrPlugin
softdepend: [Vault, PermissionsBukkit, bPermissions, zPermissions, PermissionsEX]
description: Jailr is a simple jailing plugin for Bukkit. Think of it a database-driven SimpleJail, or a stripped down version of Jail++.

commands:
  jailr:
    description: Access jailr functions.
    aliases: [jailr, jr]

permissions:
  jailr.jailer:
    description: This player has full access to jailr.
    default: op
    children:
      jailr.jail: true
      jailr.unjail: true
      jailr.setjail: true
      jailr.setunjail: true
      jailr.list: true
      jailr.jailtime: true
      jailr.immune: true
  jailr.quarantined:
    description: Removes all ability for a player to interact in the world.
    default: false
  jailr.jail:
    description: This player can jail people.
  jailr.unjail:
    description: This player can unjail people.
  jailr.setjail:
    description: This player can set the jail point.
  jailr.setunjail:
    description: This player can set the unjail point.
  jailr.list:
    description: This player can list jailed players.
  jailr.jailtime:
    description: This player can check the remaining time of a player who is tempjailed.
  jailr.immune:
    description: This player is immune to being jailed.
    default: false